name: BuildPulse CI

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    # runs-on: bp-ubuntu-latest-x64-2x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "**/go.sum"

      - name: Build binary
        run: go build -o karpenter ./cmd/controller
